// State persisted between runs
export interface DiaryState {
  lastRunAt: string | null
  lastTweetAt: string | null
  lastMentionId: string | null
  processedMentionIds: string[]
  tweetCount: number
  // Budget tracking
  totalInputTokens: number
  totalOutputTokens: number
  totalCostUsd: number
  initialBudgetUsd: number
}

// A single run's log
export interface RunLog {
  runId: string
  startedAt: string
  completedAt: string
  trigger: 'scheduled' | 'manual'
  mode: 'tweet' | 'interact' | 'both'
  // Browse context
  browseType?: 'topic' | 'account'
  browseTarget?: string  // topic keyword or @username
  browsedTweets?: Array<{ id: string; author: string; text: string }>
  // Mentions
  mentionsFound: number
  mentionsProcessed: number
  pendingMentions?: Array<{ id: string; author: string; text: string }>
  // Actions taken
  tweetsPosted: TweetLog[]
  repliesSent: ReplyLog[]
  interactions: InteractionLog[]
  // Claude's reasoning
  reflection?: string
  errors: string[]
  claudeApiCalls: ClaudeCall[]
  // Artwork
  artworkSvgPath?: string
  artworkPngPath?: string
  artworkTitle?: string
  artworkAlt?: string
}

export interface TweetLog {
  tweetId: string
  content: string
  postedAt: string
  source: 'thread'
  threadIndex?: number
  threadId?: string
  posted?: boolean  // false if failed to post (e.g. account suspended)
}

// Tweet from search results
export interface Tweet {
  id: string
  text: string
  authorId: string
  authorUsername: string
  createdAt: string
}

// Interaction log
export interface InteractionLog {
  type: 'like' | 'retweet' | 'reply'
  tweetId: string
  authorUsername: string
  originalTweet: string
  reason: string
  replyContent?: string  // for replies
  performedAt: string
  posted?: boolean  // false if failed to post (e.g. account suspended)
}

export interface ReplyLog {
  inReplyTo: string
  tweetId: string
  content: string
  postedAt: string
}

export interface ClaudeCall {
  purpose: string
  inputTokens: number
  outputTokens: number
  model: string
  thinking?: string     // Extended thinking summary
  rawResponse?: string  // For debugging - the actual Claude output
}

// Mention from Twitter
export interface Mention {
  id: string
  text: string
  authorId: string
  authorUsername: string
  createdAt: string
  conversationId: string
}

// Draft thoughts waiting to be posted
export interface Draft {
  id: string
  content: string
  createdAt: string
  source: string
  posted: boolean
}

// Interaction decision from Claude
export interface InteractionDecision {
  tweetId: string
  authorUsername: string
  action: 'like' | 'retweet' | 'reply' | 'skip'
  reason: string
  replyContent?: string
}

// Artwork generated by Claude
export interface Artwork {
  svg: string
  title?: string
  alt?: string
}

// Result from generateContent
export interface ContentResult {
  thread: string[]
  interactions: InteractionDecision[]
  mentionReplies: Array<{ mentionId: string; reply: string }>
  reflection?: string
  prioritiesCompleted?: string[]
  newPriorities?: Array<{ title: string; content: string }>
  newSearchTopics?: string[]
  artwork: Artwork
}
